logging:
  level:
    io:
      pivotal: DEBUG
eureka: # <--- ADD NEW SECTION
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port:8080}

--- # <--- ADD NEW DOCUMENT

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id}
---  # <--- ADD NEW DOCUMENT

spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-pseudofeverish-forehead.apps.steveb.ed.pcfdemo.com/eureka/ # <-- substitute your service-registry url
